-- 가장 댓글이 많이 달린 게시글을 작성한 사용자
SELECT *
FROM TBL_USER
WHERE ID IN (
	SELECT USER_ID
	FROM TBL_POST
	WHERE ID IN (
		SELECT POST_ID
		FROM TBL_REPLY
		GROUP BY POST_ID
		HAVING COUNT(POST_ID) = (
		SELECT MAX("POST_COUNT")
		FROM (
			SELECT COUNT(POST_ID) "POST_COUNT"
			FROM TBL_REPLY
			GROUP BY POST_ID
			)
		)
	)
);



-- 평균 댓글 개수보다 많이 달린 게시글
SELECT *
FROM TBL_POST
WHERE ID IN (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) >= (
		SELECT AVG(POST_COUNT)
		FROM (
			SELECT COUNT(POST_ID) "POST_COUNT"
			FROM TBL_REPLY
			GROUP BY POST_ID
			)
	)
);

