-- 사전지식 1
-- AS 만 붙이면 AS로만 접근할수 있다.
SELECT PR.PRODUCT_NAME 
FROM TBL_PRODUCT PR; 


-- 산술 연산자
SELECT 5 + 3 FROM DUAL;
SELECT 5 - 3 FROM DUAL;
SELECT 5 * 3 FROM DUAL;
SELECT 5 / 3 FROM DUAL;


-- 부호(SIGN)
SELECT SIGN(100) FROM DUAL;
SELECT SIGN(-100) FROM DUAL;


-- 논리 연산자
-- != , <>
SELECT * 
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE  <> 25300;


-- 가격대 10만원 ~ 20만원
-- BETWEEN : 범위 내
SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE BETWEEN 100000 AND 200000;

-- 문자열 연산자
-- CONCAT() : 문자열 연결
SELECT CONCAT('HELLO, ', 'WORLD') FROM DUAL;

-- SUBSTR() : 문자열 추출
SELECT SUBSTR('HELLO, WORLD', 8,5) FROM DUAL;

-- 중복 연산자
CREATE SEQUENCE SEQ_TEST;
CREATE TABLE TBL_TEST(
	ID NUMBER CONSTRAINT PK_TEST PRIMARY KEY,
	TEST_NAME VARCHAR2(255),
	TEST_PRICE NUMBER
);

INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '지우개',20000);
INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '지우개',20000);
INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '지우개',20000);
INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '지우개',30000);
INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '지우개',15000);
INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '모니터',20000);
INSERT INTO TBL_TEST
VALUES (SEQ_TEST.NEXTVAL, '키보드',30000);

CREATE SEQUENCE SEQ_TEST_ORDER;
CREATE TABLE TBL_TEST_ORDER(
	ID NUMBER CONSTRAINT PK_TEST_ORDER PRIMARY KEY,
	TEST_ORDER_NAME VARCHAR2(255),
	TEST_ID NUMBER,
	CONSTRAINT FK_TEST_ORDER_TEST FOREIGN KEY(TEST_ID)
	REFERENCES TBL_TEST(ID)
);
INSERT INTO TBL_TEST_ORDER
VALUES (SEQ_TEST_ORDER.NEXTVAL, '문 앞',1);
INSERT INTO TBL_TEST_ORDER
VALUES (SEQ_TEST_ORDER.NEXTVAL, '직접 수령',2);
INSERT INTO TBL_TEST_ORDER
VALUES (SEQ_TEST_ORDER.NEXTVAL, '직접 수령',2);

-- 중복 제거
SELECT TEST_NAME FROM TBL_TEST
UNION
SELECT TEST_ORDER_NAME FROM TBL_TEST_ORDER;

-- 중복을 제거하지 않음
SELECT TEST_NAME FROM TBL_TEST
UNION ALL
SELECT TEST_ORDER_NAME FROM TBL_TEST_ORDER;

-- MINUS
SELECT TEST_NAME FROM TBL_TEST
MINUS
SELECT TEST_ORDER_NAME FROM TBL_TEST_ORDER;


-- 문자열 함수
SELECT UPPER('abcdeFG') FROM DUAL;
SELECT LOWER('ABCDEfg') FROM DUAL;
SELECT TRIM('ABCD efg') FROM DUAL;
SELECT TRIM('          ABCD        EFG                    ') FROM DUAL;
SELECT REPLACE('APPLE','P','E') FROM DUAL;
SELECT INSTR('APPLE','L') FROM DUAL;

-- 날짜 및 시간 함수
SELECT SYSDATE FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;

-- 달 차이
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;
SELECT MONTHS_BETWEEN(SYSDATE, ADD_MONTHS(SYSDATE, 2)) FROM DUAL;
SELECT MONTHS_BETWEEN(ADD_MONTHS(SYSDATE, 2),SYSDATE) FROM DUAL;

-- 일 차이
SELECT (SYSDATE - TO_DATE('2026-01-01 12:25:00','YYYY-MM-DD HH24:MI:SS')) FROM DUAL;

-- 시 차이
SELECT (SYSDATE - TO_DATE('2026-01-01 12:25:00','YYYY-MM-DD HH24:MI:SS'))*24 FROM DUAL;

-- 분 차이
SELECT (SYSDATE - TO_DATE('2026-01-01 12:25:00','YYYY-MM-DD HH24:MI:SS'))*24 * 60 FROM DUAL;

-- 초 차이
SELECT (SYSDATE - TO_DATE('2026-01-01 12:25:00','YYYY-MM-DD HH24:MI:SS'))*24 * 60 * 60 FROM DUAL;


-- 특정 날짜부터 다음 요일
-- NEXT_DAY()

-- 1: 일
-- 2: 월
-- 3: 화
-- 4: 수
-- 5: 목
-- 6: 금
-- 7: 토

SELECT NEXT_DAY(SYSDATE,7) FROM DUAL;

-- DAY 가져오기
SELECT EXTRACT(DAY FROM NEXT_DAY(SYSDATE,7)) FROM DUAL;

-- YEAR 가져오기
SELECT EXTRACT(YEAR FROM NEXT_DAY(SYSDATE,7)) FROM DUAL;
SELECT EXTRACT(YEAR FROM TO_DATE('2026-03-18', 'YYYY-MM-DD')) FROM DUAL;

-- TO_CHAR() : 문자열로 형변환
-- 시간
SELECT TO_CHAR(TO_DATE('2026-01-01 17:15:22','YYYY-MM-DD HH24:MI:SS')) FROM DUAL;
SELECT TO_CHAR(TO_DATE('2026-01-01 17:15:22','YYYY-MM-DD HH24:MI:SS'), 'HH') FROM DUAL;
SELECT TO_CHAR(TO_DATE('2026-01-01 17:15:22','YYYY-MM-DD HH24:MI:SS'),'MI') FROM DUAL;
SELECT TO_CHAR(TO_DATE('2026-01-01 17:15:22','YYYY-MM-DD HH24:MI:SS'),'SS') FROM DUAL;

-- 숫자형 함수
SELECT ABS(-200) FROM DUAL;

-- 올림
SELECT CEIL(178.3) FROM DUAL;

-- 내림
SELECT FLOOR(175.5) FROM DUAL;

-- 나머지
SELECT MOD(5,2) FROM DUAL;

-- 반올림
SELECT ROUND(1234.4567, 3) FROM DUAL;

-- 거듭제곱
SELECT POWER(10,3) FROM DUAL;


-- 변환 함수
SELECT '100.100' + 10 FROM DUAL;
SELECT '100.100' - 10 FROM DUAL;
--SELECT 'ㄱ' - 10 FROM DUAL;
SELECT TO_NUMBER('100.100') + 10 FROM DUAL; 
SELECT TO_TIMESTAMP('2026-03-18', 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
SELECT TO_DATE('2024-02-23', 'YYYY-MM-DD') FROM DUAL;

-- CAST()
SELECT CAST(10 AS VARCHAR2(255)) FROM DUAL;
SELECT CAST('2025-03-03' AS DATE) FROM DUAL;
SELECT CAST('2025-03-03' AS TIMESTAMP) FROM DUAL;

-- NULL 치환
SELECT *
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;

--NVL : 초기값
SELECT TBT.*, TBO.*, NVL(TBO.TEST_ORDER_NAME, '없음')  
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;

-- NVL2 : 삼항 
SELECT TBT.*, TBO.*, NVL2(TBO.TEST_ORDER_NAME, '있음','없음')  
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;

-- COALESCE()
SELECT TBT.*, TBO.*, COALESCE(TBO.TEST_ORDER_NAME, TO_CHAR(TBO.TEST_ID), TBT.TEST_NAME)  
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;

-- NULLIF()
-- 두 값이 같으면 NULL
-- NUMBER만
SELECT TBT.*, TBO.*,NULLIF(TBT.TEST_PRICE,TBT.TEST_PRICE), NULLIF(TBT.TEST_PRICE, TBO.ID)
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO ON TBT.ID = TBO.TEST_ID;

-- CASE =========================
SELECT 
	TBT.*,
	TBO.*,
	CASE TBO.TEST_ORDER_NAME
		WHEN '문 앞' THEN '문 앞에 배송 됐어요.'
		WHEN '직접' THEN '직접 수령 했어요'
		ELSE '경비실에 맡겼어요'
	END
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO ON TBT.ID = TBO.TEST_ID;

--================================
SELECT 
	TBT.*,
	TBO.*,
	CASE 
		WHEN TBO.TEST_ORDER_NAME = '문 앞' THEN '문 앞에 배송 됐어요.'
		WHEN TBO.TEST_ORDER_NAME = '직접 수령' THEN '직접 수령 했어요'
		ELSE 'A'
	END
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO ON TBT.ID = TBO.TEST_ID;

-- ===============================
SELECT 
	TBT.*,
	TBO.*,
	CASE 
		WHEN TBO.TEST_ORDER_NAME IS NOT NULL THEN '문 앞에 배송 됐어요.'
		WHEN TBO.TEST_ORDER_NAME IS NULL THEN '직접 수령 했어요'
	END
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO ON TBT.ID = TBO.TEST_ID;


-- 윈도우 함수
SELECT 
	RANK() OVER(ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

SELECT 
	DENSE_RANK() OVER(ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

SELECT 
	ROW_NUMBER() OVER(ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;




SELECT 
	ROW_NUMBER() OVER(PARTITION BY TEST_NAME ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

SELECT 
--	DENSE_RANK() OVER(PARTITION BY TEST_NAME ORDER BY TEST_PRICE DESC),
	SUM(TEST_PRICE) OVER(PARTITION BY TEST_NAME),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;




SELECT 
	TEST_NAME,
	TEST_PRICE,
	LEAD(TEST_PRICE, 1) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;



SELECT 
	TEST_NAME,
	TEST_PRICE,
	LAG(TEST_PRICE) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;



SELECT 
	TEST_NAME,
	TEST_PRICE,
	FIRST_VALUE(TEST_PRICE) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;



SELECT 
	TEST_NAME,
	TEST_PRICE,
	LAST_VALUE(TEST_PRICE) OVER(ORDER BY TEST_PRICE DESC)
FROM TBL_TEST;



SELECT 
	TEST_NAME,
	TEST_PRICE,
	NTH_VALUE(TEST_PRICE,6) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;




SELECT 
	TEST_NAME,
	TEST_PRICE,
	SUM(TEST_PRICE) OVER(PARTITION BY TEST_NAME)
FROM TBL_TEST
GROUP BY CUBE(TEST_NAME, TEST_PRICE);