CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COMMENT VARCHAR2(255),
	ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(255),
	REPLY_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	POST_ID NUMBER,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID),
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_POST(ID)
);


/*
   요구사항
   유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
   아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
   체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
   아이들은 여러 번 체험학습에 등록할 수 있어요.
*/
-- TBL_CHILD
-- 이름, 나이, 성별

-- TBL_PARENT
-- 이름, 나이, 주소, 전화번호, 성별


-- 체험 학습

-- 체험 학습 이미지

-- 신청



CREATE SEQUENCE SEQ_PARENT;
CREATE TABLE TBL_PARENT(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_NAME VARCHAR2(255) NOT NULL,
	PARENT_AGE NUMBER NOT NULL,
	PARENT_ADDRESS VARCHAR2(255) NOT NULL,
	PARENT_PHONE VARCHAR2(255) UNIQUE NOT NULL,
	PARENT_GENDER VARCHAR2(255) NOT NULL,
	CHILD_ID NUMBER,
	CONSTRAINT FK_PARENT_CHILD FOREIGN KEY(CHILD_ID)
	REFERENCES TBL_CHILD(ID)
);



CREATE SEQUENCE SEQ_CHILD;
CREATE TABLE TBL_CHILD(
	ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
	CHILD_NAME VARCHAR2(255) NOT NULL,
	CHILD_AGE NUMBER,
	CHILD_GENDER CHAR(5)
);

CREATE SEQUENCE SEQ_FIELD_TRIP;
CREATE TABLE TBL_FIELD_TRIP(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
	FIELD_TRIP_TITLE VARCHAR2(255) NOT NULL,
	FIELD_TRIP_CONTENT VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_FIELD_TRIP_IMAGE;
CREATE TABLE TBL_FIELD_TRIP_IMAGE(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP_IMAGE PRIMARY KEY,
	FIELD_TRIP_IMAGE_PATH VARCHAR2(255),
	FIELD_TRIP_IMAGE_NAME VARCHAR2(255),
	FIELD_TRIP_ID NUMBER,
	CONSTRAINT FK_FILELD_TRIP_IMAGE_TRIP FOREIGN KEY(FIELD_TRIP_ID)
	REFERENCES TBL_FIELD_TRIP(ID)
);

CREATE SEQUENCE SEQ_APPLY;
CREATE TABLE TBL_APPLY(
	ID NUMBER CONSTRAINT PK_APPLY PRIMARY KEY,
   	CHILD_ID NUMBER,
   	FIELD_TRIP_ID NUMBER,
   	CONSTRAINT FK_APPLY_CHILD FOREIGN KEY(CHILD_ID)
   	REFERENCES TBL_CHILD(ID),
   	CONSTRAINT FK_APPLY_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
   	REFERENCES TBL_FIELD_TRIP(ID)
);

/*
 
   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/

-- TBL_COMPANY
-- 기업

CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255) UNIQUE NOT NULL,
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_PHONE VARCHAR2(255),
	COMPANY_TYPE VARCHAR2(255) NOT NULL,
	CONSTRAINT COMPANY_BAN_TYPE CHECK(COMPANY_TYPE IN ('스타트업','중소기업','중견기업','대기업'))
);
-- TBL_ADVERTISEMENT
-- 광고 
-- 제목, 내용 
CREATE SEQUENCE SEQ_ADVERTISEMENT;
CREATE TABLE TBL_ADVERTISEMENT(
	ID NUMBER CONSTRAINT PK_ADVERTISEMENT PRIMARY KEY,
	ADVERTISEMENT_TITLE VARCHAR2(255) NOT NULL,
	ADVERTISEMENT_CONTENT VARCHAR2(255) NOT NULL
);

-- 신청
CREATE SEQUENCE SEQ_AD_APPLY;
CREATE TABLE TBL_AD_APPLY(
	ID NUMBER CONSTRAINT PK_AD_APPLY PRIMARY KEY,
	COMPANY_ID NUMBER,
	ADVERTISEMENT_ID NUMBER,
	CONSTRAINT FK_AD_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_AD_APPLY_ADVERTISEMENT FOREIGN KEY(ADVERTISEMENT_ID)
	REFERENCES TBL_ADVERTISEMENT(ID)
	);

-- TBL_CATEGORY
-- 대카테고리
CREATE SEQUENCE SEQ_BIG_CATEGORY;
CREATE TABLE TBL_BIG_CATEGORY(
	ID NUMBER CONSTRAINT PK_BIG_CATEGORY PRIMARY KEY,
	BIG_CATEGORY_NAME VARCHAR2(255) NOT NULL,
	ADVETISEMENT_ID NUMBER,
	CONSTRAINT FK_BIG_CATEGORY_ADVERTISEMENT FOREIGN KEY(ADVETISEMENT_ID)
	REFERENCES TBL_ADVERTISEMENT(ID)
	);


-- 중
CREATE SEQUENCE SEQ_MIDDLE_CATEGORY;
CREATE TABLE TBL_MIDDLE_CATEGORY(
	ID NUMBER CONSTRAINT PK_MIDDLE_CATEGORY PRIMARY KEY,
	MIDDLE_CATEGORY_NAME VARCHAR2(255) NOT NULL,
	BIG_CATEGORY_ID NUMBER,
	CONSTRAINT FK_MIDDLE_CATEGORY_BIG_CATEGORY FOREIGN KEY(BIG_CATEGORY_ID)
	REFERENCES TBL_BIG_CATEGORY(ID)
	);


-- 소
CREATE SEQUENCE SEQ_SMALL_CATEGORY;
CREATE TABLE TBL_SMALL_CATEGORY(
	ID NUMBER CONSTRAINT PK_SMALL_CATEGORY PRIMARY KEY,
	SMALL_CATEGORY_NAME VARCHAR2(255) NOT NULL,
	MIDDLE_CATEGORY_ID NUMBER,
	CONSTRAINT FK_SMALL_CATEGORY_MIDDLE_CATEGORY FOREIGN KEY(MIDDLE_CATEGORY_ID)
	REFERENCES TBL_MIDDLE_CATEGORY(ID)
	);
