/*
	GROUP BY부터 생각을 많이 해야한다
	FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY
*/

SELECT * FROM TBL_POST;
SELECT * FROM TBL_REPLY;
SELECT * FROM TBL_USER;

SELECT TBP.* , TBU.USER_EMAIL 
FROM TBL_POST TBP
JOIN TBL_USER TBU ON TBP.USER_ID = TBU.ID;


-- 조인을 실행시 FK가 있는 곳부터 코드 작성

SELECT TBR.REPLY_CONTENT , TBP.POST_TITLE 
FROM TBL_REPLY TBR
JOIN TBL_POST TBP ON TBR.POST_ID = TBP.ID;


-- 댓글, 유저테이블 조인후
-- 댓글의 작성자와 댓글 내용을 조회
SELECT TBU.USER_EMAIL ,TBR.REPLY_CONTENT
FROM TBL_REPLY TBR
JOIN TBL_USER TBU ON TBR.USER_ID = TBU.ID;


-- 3개 조인
-- 게시글 제목, 댓글 내용, 작성자
SELECT TBP.POST_TITLE , TBR.REPLY_CONTENT , TBU.USER_EMAIL 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
WHERE POST_TITLE LIKE '%유중의 미%';

-- 하나만 같은 경우 중복들 제거
SELECT DISTINCT TBP.POST_TITLE
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
WHERE POST_TITLE LIKE '%유중의 미%';

-- 하나만 같아도 모두 같지 않으므로 중복 제거 X
SELECT DISTINCT TBP.POST_TITLE , TBR.REPLY_CONTENT , TBU.USER_EMAIL
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
WHERE POST_TITLE LIKE '%유중의 미%';

-- 댓글 2개이상 달린 게시글의 작성자 이메일, 주소를 조회하기
SELECT *
FROM TBL_REPLY;

SELECT DISTINCT TBU.USER_EMAIL , TBU.USER_ADDRESS 
FROM (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) >= 2
) TBR
JOIN TBL_POST TBP ON TBR.POST_ID = TBP.ID
JOIN TBL_USER TBU ON TBP.USER_ID = TBU.ID

-- 내용에 뀨트북이 들어간 게시글의 달린 댓글 조회
SELECT TBR.* 
FROM TBL_REPLY TBR
JOIN TBL_POST TBP ON TBR.POST_ID = TBP.ID 
WHERE TBP.POST_TITLE LIKE '%뀨트북%' OR TBP.POST_CONTENT LIKE '%뀨트북%';

-- 내용에 포도가 들어간 글을 작성한 작성자의 이메일 조회
SELECT TBU.USER_EMAIL 
FROM TBL_POST TBP
JOIN TBL_USER TBU 
	ON TBP.USER_ID = TBU.ID
--	AND TBP.POST_CONTENT LIKE '%포도%' 
--	OR TBP.POST_TITLE LIKE '%포도%';

--	위,아래 둘 다 사용 가능
	
--WHERE TBP.POST_CONTENT LIKE '%포도%' OR TBP.POST_TITLE LIKE '%포도%';


-- 2000년생 유저가 작성한 댓글 조회
SELECT TBR.REPLY_CONTENT "댓글"
FROM TBL_REPLY TBR
JOIN TBL_USER TBU ON TBR.USER_ID = TBU.ID 
WHERE TBU.USER_BIRTH >= TO_DATE('2000', 'YYYY') AND TBU.USER_BIRTH <= TO_DATE('2001','YYYY');

-- 가장 나이가 어린 사용자가 작성한 게시글 조회
-- 1.
SELECT TBP.POST_TITLE , TBP.POST_CONTENT 
FROM TBL_POST TBP
JOIN (
	SELECT ID 
	FROM TBL_USER
	WHERE USER_BIRTH = (
		SELECT MAX(USER_BIRTH)
		FROM TBL_USER
	)
) TBU ON TBP.USER_ID = TBU.ID;

-- 2.
SELECT TBP.*
FROM TBL_POST TBP
JOIN (
   SELECT *
   FROM TBL_USER
   ORDER BY USER_BIRTH DESC
   FETCH FIRST 1 ROWS ONLY
) TBU
ON TBP.USER_ID = TBU.ID;

-- 3.
SELECT *
FROM (
   SELECT *
   FROM TBL_USER
   ORDER BY USER_BIRTH DESC
)
WHERE ROWNUM = 1;
-- 주소가 '구'로 끝나는 유저가 작성한 게시글에 달린 모든 댓글 조회

--SELECT TBR.REPLY_CONTENT
--FROM TBL_REPLY TBR
--JOIN (
--	SELECT TBU.ID
--	FROM TBL_POST TBP
--	JOIN (
--		SELECT ID 
--		FROM TBL_USER
--		WHERE USER_ADDRESS LIKE '%구'
--	) TBU ON TBP.USER_ID  = TBU.ID
--) tbu ON TBR.USER_ID = tbu.ID;

SELECT TBP.USER_ID, TBR.*
FROM (
   SELECT TBU.*
   FROM TBL_USER TBU
   WHERE TBU.USER_ADDRESS LIKE '%구'
) TBU
JOIN TBL_POST TBP
ON TBP.USER_ID = TBU.ID
JOIN TBL_REPLY TBR
ON TBR.POST_ID = TBP.ID;

-- 평균 댓글 개수보다 작게 달린 게시글을 작성한 유저 조회
SELECT TBU.*
FROM (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID 
	HAVING COUNT(POST_ID) < (
		SELECT AVG(COUNT(POST_ID))
		FROM TBL_REPLY
		GROUP BY POST_ID
	)
) TBR
JOIN TBL_POST TBP ON TBR.POST_ID = TBP.ID
JOIN TBL_USER TBU ON TBP.USER_ID = TBU.ID;
